# This is a basic workflow to help you get started with Actions
name: Deploy Gatsby to Firebase Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        NODE_ENV=production
        yarn --frozen-lockfile
        cd ./node_modules/gatsby-source-strapi
        yarn install
        cd ../../
    
    - name: Build Gatsby
      run: yarn build
      env:
        API_URL: "http://akeno.mydns.jp:8383"

    - name: Setup Firebase CLI
      run: npm install -g firebase-tools
    - name: Deploy Firebase
      run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}

    - name: Webhook on success
      if: ${{ success() }}
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        headers: '{"repository": "joelwmale/webhook-action"}'
        body: '{"value1": "成功！","value2": "${{ github.event_name }} by ${{ github.actor }} on ${{ github.ref }}", "value3": "${{ github.event.head_commit.message }}"}'

    - name: Webhook on failure
      if: ${{ failure() }}
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        headers: '{"repository": "joelwmale/webhook-action"}'
        body: '{"value1": "失敗…","value2": "${{ github.event_name }} by ${{ github.actor }} on ${{ github.ref }}", "value3": "${{ github.event.head_commit.message }}"}'
