# This is a basic workflow to help you get started with Actions
name: Deploy Gatsby to Firebase Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Environment Variables from Dotenv
      uses: c-py/action-dotenv-to-setenv@v1
      with:
        env-file: .env.production

    - name: Install dependencies
      run: |
        NODE_ENV=production
        yarn --frozen-lockfile
    - name: Build Gatsby
      run: yarn build
    - name: Deploy Firebase
      run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}
